### ISSUE TITLE
a script to preview only the renderer part in the browser

### ISSUE THREAD

**Issue by massifrg** [gunters63/vite-electron-builder#1]
I'd need a script in `package.json` to preview only the renderer part in the browser.
I'd like my app to work both on a server and inside a standalone, desktop, electron-based app.
The script I'm asking for would preview only the server-based version.
I tried this:
```
  // "scripts" section of package.json
  "dev": "vite",
```
but it does not work.
(BTW thanks for this project, it solved me the problems I had with electron's preload)

**Comment by gunters63** [comment]
Hi @massifrg,

Sorry I cannot help you. I just forked the master repo (https://github.com/cawa-93/vite-electron-builder) for playing around a bit and trying out the Github actions of it. I didn't make any changes. I will likely delete the repo again after playing around.

You should ask your question in the master repo :).

**Comment by gunters63** [comment]
By the way, I wasn't aware of the fact that Github now offers unlimited private repos for free. I would have made this playground repo private from the start if I knew at fork time :)

**Comment by massifrg** [comment]
I overlook that it was a fork. I'll post my request in the master repo.
Thanks for your reply.
